version: '3'

services:
 app1:
    image: vdorsonnens/pelican-sample:v1
    expose:
      - 8000
    ports:
      - 8000:8000
 app2:
    image: vdorsonnens/pelican-sample:v2
    expose:
      - 8001
    ports:
      - 8001:8001